describe('Settings#template', () => {
  it('should render correctly', () => {
    const selectors = [
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > h1.base-header.base-header--1:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--theme:nth-child(2) > h2.base-section__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--theme:nth-child(2) > div.base-section__content:nth-child(2) > div.base-select.base-select--theme-change-theme:nth-child(1) > span.base-section__label-wrapper.base-select__label-wrapper:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--theme:nth-child(2) > div.base-section__content:nth-child(2) > div.base-select.base-select--theme-change-theme:nth-child(1) > div.base-section__form-wrapper.base-select__form-wrapper:nth-child(2) > select.base-select__input:nth-child(1) > option:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--theme:nth-child(2) > div.base-section__content:nth-child(2) > div.base-select.base-select--theme-change-theme:nth-child(1) > div.base-section__form-wrapper.base-select__form-wrapper:nth-child(2) > select.base-select__input:nth-child(1) > option:nth-child(2)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--text:nth-child(3) > h2.base-section__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--text:nth-child(3) > div.base-section__content:nth-child(2) > div.base-input.base-input--text-font-size:nth-child(1) > span.base-section__label-wrapper.base-input__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--text:nth-child(3) > div.base-section__content:nth-child(2) > div.base-input.base-input--text-font-size:nth-child(1) > div.base-section__form-wrapper.base-input__form-wrapper.base-input__form-wrapper--unit:nth-child(2) > input.base-input__input.base-input__input--unit:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--text:nth-child(3) > div.base-section__content:nth-child(2) > div.base-input.base-input--text-paragraph-indent:nth-child(2) > span.base-section__label-wrapper.base-input__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--text:nth-child(3) > div.base-section__content:nth-child(2) > div.base-input.base-input--text-paragraph-indent:nth-child(2) > div.base-section__form-wrapper.base-input__form-wrapper.base-input__form-wrapper--unit:nth-child(2) > input.base-input__input.base-input__input--unit:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--text:nth-child(3) > div.base-section__content:nth-child(2) > div.base-input.base-input--text-line-height:nth-child(3) > span.base-section__label-wrapper.base-input__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--text:nth-child(3) > div.base-section__content:nth-child(2) > div.base-input.base-input--text-line-height:nth-child(3) > div.base-section__form-wrapper.base-input__form-wrapper.base-input__form-wrapper--unit:nth-child(2) > input.base-input__input.base-input__input--unit:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--texteditor:nth-child(4) > h2.base-section__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--texteditor:nth-child(4) > div.base-section__content:nth-child(2) > div.base-input.base-input--texteditor-max-width:nth-child(1) > span.base-section__label-wrapper.base-input__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--texteditor:nth-child(4) > div.base-section__content:nth-child(2) > div.base-input.base-input--texteditor-max-width:nth-child(1) > div.base-section__form-wrapper.base-input__form-wrapper.base-input__form-wrapper--unit:nth-child(2) > input.base-input__input.base-input__input--unit:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--texteditor:nth-child(4) > div.base-section__content:nth-child(2) > div.base-input.base-input--texteditor-margin-top:nth-child(2) > span.base-section__label-wrapper.base-input__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--texteditor:nth-child(4) > div.base-section__content:nth-child(2) > div.base-input.base-input--texteditor-margin-top:nth-child(2) > div.base-section__form-wrapper.base-input__form-wrapper.base-input__form-wrapper--unit:nth-child(2) > input.base-input__input.base-input__input--unit:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--texteditor:nth-child(4) > div.base-section__content:nth-child(2) > div.base-input.base-input--texteditor-margin-bottom:nth-child(3) > span.base-section__label-wrapper.base-input__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--texteditor:nth-child(4) > div.base-section__content:nth-child(2) > div.base-input.base-input--texteditor-margin-bottom:nth-child(3) > div.base-section__form-wrapper.base-input__form-wrapper.base-input__form-wrapper--unit:nth-child(2) > input.base-input__input.base-input__input--unit:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--stats:nth-child(5) > h2.base-section__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--stats:nth-child(5) > div.base-section__content:nth-child(2) > div.base-select.base-select--stats-formula-ingredient:nth-child(1) > span.base-section__label-wrapper.base-select__label-wrapper:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--stats:nth-child(5) > div.base-section__content:nth-child(2) > div.base-select.base-select--stats-formula-ingredient:nth-child(1) > div.base-section__form-wrapper.base-select__form-wrapper:nth-child(2) > select.base-select__input:nth-child(1) > option:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--stats:nth-child(5) > div.base-section__content:nth-child(2) > div.base-select.base-select--stats-formula-ingredient:nth-child(1) > div.base-section__form-wrapper.base-select__form-wrapper:nth-child(2) > select.base-select__input:nth-child(1) > option:nth-child(2)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--stats:nth-child(5) > div.base-section__content:nth-child(2) > div.base-select.base-select--stats-formula-ingredient:nth-child(1) > div.base-section__form-wrapper.base-select__form-wrapper:nth-child(2) > select.base-select__input:nth-child(1) > option:nth-child(3)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--stats:nth-child(5) > div.base-section__content:nth-child(2) > div.base-select.base-select--stats-formula-ingredient:nth-child(1) > div.base-section__form-wrapper.base-select__form-wrapper:nth-child(2) > select.base-select__input:nth-child(1) > option:nth-child(4)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--stats:nth-child(5) > div.base-section__content:nth-child(2) > div.base-input.base-input--stats-formula-divider:nth-child(2) > span.base-section__label-wrapper.base-input__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--stats:nth-child(5) > div.base-section__content:nth-child(2) > div.base-input.base-input--stats-formula-divider:nth-child(2) > div.base-section__form-wrapper.base-input__form-wrapper:nth-child(2) > input.base-input__input:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--stats:nth-child(5) > div.base-section__content:nth-child(2) > div.base-text.base-text--stats-formula-tip:nth-child(3)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar:nth-child(6) > h2.base-section__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar:nth-child(6) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--statusbar-is-visible:nth-child(1) > span.base-section__label-wrapper.base-toggle__label-wrapper:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar:nth-child(6) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--statusbar-is-visible:nth-child(1) > div.base-section__form-wrapper.base-toggle__form-wrapper.base-toggle__form-wrapper--active:nth-child(2) > div.base-toggle__input.base-toggle__input--active:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar-content:nth-child(7) > h2.base-section__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar-content:nth-child(7) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--statusbar-content-words:nth-child(1) > span.base-section__label-wrapper.base-toggle__label-wrapper:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar-content:nth-child(7) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--statusbar-content-words:nth-child(1) > div.base-section__form-wrapper.base-toggle__form-wrapper.base-toggle__form-wrapper--active:nth-child(2) > div.base-toggle__input.base-toggle__input--active:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar-content:nth-child(7) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--statusbar-content-pages:nth-child(2) > span.base-section__label-wrapper.base-toggle__label-wrapper:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar-content:nth-child(7) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--statusbar-content-pages:nth-child(2) > div.base-section__form-wrapper.base-toggle__form-wrapper.base-toggle__form-wrapper--active:nth-child(2) > div.base-toggle__input.base-toggle__input--active:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar-content:nth-child(7) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--statusbar-content-paragraphs:nth-child(3) > span.base-section__label-wrapper.base-toggle__label-wrapper:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar-content:nth-child(7) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--statusbar-content-paragraphs:nth-child(3) > div.base-section__form-wrapper.base-toggle__form-wrapper.base-toggle__form-wrapper--active:nth-child(2) > div.base-toggle__input.base-toggle__input--active:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar-content:nth-child(7) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--statusbar-content-characters:nth-child(4) > span.base-section__label-wrapper.base-toggle__label-wrapper:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--statusbar-content:nth-child(7) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--statusbar-content-characters:nth-child(4) > div.base-section__form-wrapper.base-toggle__form-wrapper.base-toggle__form-wrapper--active:nth-child(2) > div.base-toggle__input.base-toggle__input--active:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--misc:nth-child(8) > h2.base-section__title:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--misc:nth-child(8) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--misc-spellchecker:nth-child(1) > span.base-section__label-wrapper.base-toggle__label-wrapper:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--misc:nth-child(8) > div.base-section__content:nth-child(2) > div.base-toggle.base-toggle--misc-spellchecker:nth-child(1) > div.base-section__form-wrapper.base-toggle__form-wrapper.base-toggle__form-wrapper--active:nth-child(2) > div.base-toggle__input.base-toggle__input--active:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--misc:nth-child(8) > div.base-section__content:nth-child(2) > div.base-select.base-select--misc-language:nth-child(2) > span.base-section__label-wrapper.base-select__label-wrapper:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--misc:nth-child(8) > div.base-section__content:nth-child(2) > div.base-select.base-select--misc-language:nth-child(2) > div.base-section__form-wrapper.base-select__form-wrapper:nth-child(2) > select.base-select__input:nth-child(1) > option:nth-child(1)',
      '#app > div.sidebar-panel.sidebar-panel--settings:nth-child(2) > section.base-section.base-section--misc:nth-child(8) > div.base-section__content:nth-child(2) > div.base-select.base-select--misc-language:nth-child(2) > div.base-section__form-wrapper.base-select__form-wrapper:nth-child(2) > select.base-select__input:nth-child(1) > option:nth-child(2)'
    ]

    cy.clearLocalStorage()
    cy.visit('/')

    cy.get('.sidebar-button--settings')
      .click()

    selectors.forEach((selector) => {
      cy.get(`${selector}`)
        .should('exist')
    })
  })
})
