export default {
  parentNotAnArray: 'HV_VAL_STRING_TYPE_GUARD_PARENT_NOT_AN_ARRAY',
  itemNotAnArray: 'HV_VAL_STRING_TYPE_GUARD_ITEM_NOT_AN_ARRAY',
  itemLengthError: 'HV_VAL_STRING_TYPE_GUARD_ITEM_LENGTH_ERROR',
  itemTypesError: 'HV_VAL_STRING_TYPE_GUARD_ITEM_TYPES_ERROR',
  unknownOperator: 'HV_VAL_STRING_TYPE_GUARD_UNKNOWN_OPERATOR'
}
