<template>
  <sidebar-base>
    <sidebar-button
      slot="top"
      :action="newFile"
      :active-panel="openPanel"
      :alt="$t('general.newFile')"
      :toggle="false"
      icon="newfile"
      name="newfile"
    />
    <sidebar-button
      slot="top"
      :action="buttonDownload"
      :active-panel="openPanel"
      :alt="$t('general.download.title')"
      :toggle="false"
      icon="download"
      name="download"
    />
    <sidebar-button
      slot="bottom"
      :action="togglePanel"
      :active-panel="openPanel"
      :alt="$t('stats.title')"
      :toggle="true"
      icon="stats"
      name="stats"
    />
    <sidebar-button
      slot="bottom"
      :action="togglePanel"
      :active-panel="openPanel"
      :alt="$t('settings.title')"
      :toggle="true"
      icon="settings"
      name="settings"
    />
  </sidebar-base>
</template>

<script src='./Sidebar.js'></script>
<style  src='./Sidebar.scss' lang='scss' scoped></style>
