<template functional>
  <base-section
    :title="parent.$t('settings.misc.title')"
    name="misc"
  >
    <base-toggle
      :title="parent.$t('settings.misc.spellChecker.title')"
      action="changeState"
      item="settings.misc.spellChecker"
      name="misc-spellchecker"
    />
    <base-select
      :labels="parent.$t('settings.misc.language.labels')"
      :title="parent.$t('settings.misc.language.title')"
      action="changeState"
      item="settings.misc.language"
      name="misc-language"
    />
  </base-section>
</template>
