<template functional>
  <base-section
    :title="parent.$t('settings.statusBarContent.title')"
    name="statusbar-content"
  >
    <base-toggle
      :title="parent.$t('stats.longNames.words')"
      action="changeState"
      item="settings.statusBar.showContent.words"
      name="statusbar-content-words"
    />
    <base-toggle
      :title="parent.$t('stats.longNames.pages')"
      action="changeState"
      item="settings.statusBar.showContent.pages"
      name="statusbar-content-pages"
    />
    <base-toggle
      :title="parent.$t('stats.longNames.paragraphs')"
      action="changeState"
      item="settings.statusBar.showContent.paragraphs"
      name="statusbar-content-paragraphs"
    />
    <base-toggle
      :title="parent.$t('stats.longNames.characters')"
      action="changeState"
      item="settings.statusBar.showContent.characters"
      name="statusbar-content-characters"
    />
  </base-section>
</template>
