<template functional>
  <base-section
    name='statusbar-content'
    :title='parent.$t("settings.statusBarContent.title")'
  >
    <base-toggle
      action='changeState'
      item='settings.statusBar.showContent.words'
      name='statusbar-content-words'
      :title='parent.$t("stats.longNames.words")'
    />
    <base-toggle
      action='changeState'
      item='settings.statusBar.showContent.pages'
      name='statusbar-content-pages'
      :title='parent.$t("stats.longNames.pages")'
    />
    <base-toggle
      action='changeState'
      item='settings.statusBar.showContent.paragraphs'
      name='statusbar-content-paragraphs'
      :title='parent.$t("stats.longNames.paragraphs")'
    />
    <base-toggle
      action='changeState'
      item='settings.statusBar.showContent.characters'
      name='statusbar-content-characters'
      :title='parent.$t("stats.longNames.characters")'
    />
  </base-section>
</template>
