<template functional>
  <base-section
    :title="parent.$t('settings.stats.title')"
    name="stats"
  >
    <base-select
      :labels="parent.$t('settings.stats.pageFormulaMainIngredient.labels')"
      :title="parent.$t('settings.stats.pageFormulaMainIngredient.title')"
      action="changeState"
      item="settings.stats.pageFormulaMainIngredient"
      name="stats-formula-ingredient"
    />
    <base-input
      :error-tip="parent.$t('settings.stats.pageFormulaDivider.errorTip')"
      :title="parent.$t('settings.stats.pageFormulaDivider.title')"
      action="changeState"
      item="settings.stats.pageFormulaDivider"
      name="stats-formula-divider"
    />
    <base-text
      :text="parent.$t('settings.stats.formulaTip')"
      name="stats-formula-tip"
    />
  </base-section>
</template>
