<template functional>
  <base-section
    name='text'
    :title='parent.$t("settings.text.title")'
  >
    <base-input
      action='changeState'
      :errorTip='parent.$t("settings.text.fontSize.errorTip")'
      item='settings.editor.text.fontSize'
      name='text-font-size'
      :title='parent.$t("settings.text.fontSize.title")'
      unit='px'
    />
    <base-input
      action='changeState'
      :errorTip='parent.$t("settings.text.paragraphIndent.errorTip")'
      item='settings.editor.text.paragraphIndent'
      name='text-paragraph-indent'
      :title='parent.$t("settings.text.paragraphIndent.title")'
      unit='px'
    />
    <base-input
      action='changeState'
      :errorTip='parent.$t("settings.text.lineHeight.errorTip")'
      item='settings.editor.text.lineHeight'
      name='text-line-height'
      :title='parent.$t("settings.text.lineHeight.title")'
      unit='em'
    />
  </base-section>
</template>
