<template functional>
  <base-section
    name='texteditor'
    :title='parent.$t("settings.textEditor.title")'
  >
    <base-input
      action='changeState'
      :errorTip='parent.$t("settings.textEditor.maxWidth.errorTip")'
      item='settings.editor.window.maxWidth'
      name='texteditor-max-width'
      :title='parent.$t("settings.textEditor.maxWidth.title")'
      unit='px'
    />
    <base-input
      action='changeState'
      :errorTip='parent.$t("settings.textEditor.marginTop.errorTip")'
      item='settings.editor.window.marginTop'
      name='texteditor-margin-top'
      :title='parent.$t("settings.textEditor.marginTop.title")'
      unit='px'
    />
    <base-input
      action='changeState'
      :errorTip='parent.$t("settings.textEditor.marginBottom.errorTip")'
      item='settings.editor.window.marginBottom'
      name='texteditor-margin-bottom'
      :title='parent.$t("settings.textEditor.marginBottom.title")'
      unit='px'
    />
  </base-section>
</template>
