<template functional>
  <base-section
    :title="parent.$t('settings.textEditor.title')"
    name="texteditor"
  >
    <base-input
      :error-tip="parent.$t('settings.textEditor.maxWidth.errorTip')"
      :title="parent.$t('settings.textEditor.maxWidth.title')"
      action="changeState"
      item="settings.editor.window.maxWidth"
      name="texteditor-max-width"
      unit="px"
    />
    <base-input
      :error-tip="parent.$t('settings.textEditor.marginTop.errorTip')"
      :title="parent.$t('settings.textEditor.marginTop.title')"
      action="changeState"
      item="settings.editor.window.marginTop"
      name="texteditor-margin-top"
      unit="px"
    />
    <base-input
      :error-tip="parent.$t('settings.textEditor.marginBottom.errorTip')"
      :title="parent.$t('settings.textEditor.marginBottom.title')"
      action="changeState"
      item="settings.editor.window.marginBottom"
      name="texteditor-margin-bottom"
      unit="px"
    />
  </base-section>
</template>
